// <auto-generated />
using System;
using Locadora.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Locadora.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191129020131_AddAtbIdentTableClient")]
    partial class AddAtbIdentTableClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Locadora.Models.Carro", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoModelo");

                    b.Property<string>("Codigo");

                    b.Property<string>("CodigoFipe");

                    b.Property<string>("Combustivel");

                    b.Property<string>("Cor");

                    b.Property<string>("IdMarca");

                    b.Property<string>("IdModelo");

                    b.Property<string>("IdentVeiculo");

                    b.Property<string>("Imagem");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nome");

                    b.Property<string>("Placa")
                        .IsRequired();

                    b.Property<decimal>("Preco");

                    b.Property<string>("Status");

                    b.Property<int>("TipoVeiculo");

                    b.Property<string>("Valor");

                    b.Property<decimal>("ValorMensal");

                    b.Property<double>("ValorPorDia");

                    b.Property<double>("ValorPorHora");

                    b.HasKey("IdVeiculo");

                    b.ToTable("CARRO");
                });

            modelBuilder.Entity("Locadora.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarroId");

                    b.Property<string>("CategoriaCnh");

                    b.Property<string>("Cnh");

                    b.Property<string>("Cpf");

                    b.Property<int?>("Ident");

                    b.Property<int?>("MotoId");

                    b.Property<string>("Nome");

                    b.Property<string>("PossuiReserva");

                    b.Property<string>("Rg");

                    b.Property<string>("Senha");

                    b.Property<string>("Status");

                    b.HasKey("IdCliente");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("Locadora.Models.ClienteLogado", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Locadora.Models.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarroIdVeiculo");

                    b.Property<string>("Codigo");

                    b.Property<int?>("MotoIdVeiculo");

                    b.Property<string>("Nome");

                    b.HasKey("ModeloId");

                    b.HasIndex("CarroIdVeiculo");

                    b.HasIndex("MotoIdVeiculo");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("Locadora.Models.Moto", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoModelo");

                    b.Property<string>("Codigo");

                    b.Property<string>("CodigoFipe");

                    b.Property<string>("Combustivel");

                    b.Property<string>("Cor");

                    b.Property<string>("IdMarca");

                    b.Property<string>("IdModelo");

                    b.Property<string>("IdentVeiculo");

                    b.Property<string>("Imagem");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nome");

                    b.Property<string>("Placa")
                        .IsRequired();

                    b.Property<decimal>("Preco");

                    b.Property<string>("Status");

                    b.Property<int>("TipoVeiculo");

                    b.Property<string>("Valor");

                    b.Property<decimal>("ValorMensal");

                    b.Property<double>("ValorPorDia");

                    b.Property<double>("ValorPorHora");

                    b.HasKey("IdVeiculo");

                    b.ToTable("MOTO");
                });

            modelBuilder.Entity("Locadora.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteIdCliente");

                    b.Property<bool?>("Credito");

                    b.Property<bool?>("Debito");

                    b.Property<bool?>("Dinheiro");

                    b.Property<DateTime>("DtVeicDevolvido");

                    b.Property<string>("NroCartao");

                    b.Property<int?>("ReservaIdReserva");

                    b.Property<string>("Status");

                    b.Property<double>("ValorPagamento");

                    b.Property<double>("ValorTotalReserva");

                    b.Property<double>("ValorTroco");

                    b.HasKey("IdPagamento");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("ReservaIdReserva");

                    b.ToTable("PAGAMENTO");
                });

            modelBuilder.Entity("Locadora.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarroId");

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime?>("DataPrevisaoDevolucao");

                    b.Property<DateTime?>("DataReserva");

                    b.Property<DateTime?>("DataVeiculoDevolvido");

                    b.Property<int?>("MotoId");

                    b.Property<string>("Status");

                    b.Property<decimal>("ValorTotal");

                    b.Property<double>("ValorTotalDiaria");

                    b.HasKey("IdReserva");

                    b.HasIndex("CarroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MotoId");

                    b.ToTable("RESERVA");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Locadora.Models.Modelo", b =>
                {
                    b.HasOne("Locadora.Models.Carro")
                        .WithMany("Modelos")
                        .HasForeignKey("CarroIdVeiculo");

                    b.HasOne("Locadora.Models.Moto")
                        .WithMany("Modelos")
                        .HasForeignKey("MotoIdVeiculo");
                });

            modelBuilder.Entity("Locadora.Models.Pagamento", b =>
                {
                    b.HasOne("Locadora.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("Locadora.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaIdReserva");
                });

            modelBuilder.Entity("Locadora.Models.Reserva", b =>
                {
                    b.HasOne("Locadora.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId");

                    b.HasOne("Locadora.Models.Cliente", "Cliente")
                        .WithMany("Reserva")
                        .HasForeignKey("ClienteId");

                    b.HasOne("Locadora.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Locadora.Models.ClienteLogado")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Locadora.Models.ClienteLogado")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Locadora.Models.ClienteLogado")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Locadora.Models.ClienteLogado")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
