// <auto-generated />
using System;
using Locadora.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Locadora.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191118233303_addattVeiculo")]
    partial class addattVeiculo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Locadora.Models.Carro", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoModelo");

                    b.Property<string>("Codigo");

                    b.Property<string>("CodigoFipe");

                    b.Property<string>("Combustivel");

                    b.Property<string>("Cor");

                    b.Property<string>("IdMarca");

                    b.Property<string>("IdModelo");

                    b.Property<string>("IdentVeiculo");

                    b.Property<string>("Imagem");

                    b.Property<string>("Marca");

                    b.Property<string>("MesReferencia");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nome");

                    b.Property<string>("Placa")
                        .IsRequired();

                    b.Property<double>("Preco");

                    b.Property<string>("Status");

                    b.Property<int>("TipoVeiculo");

                    b.Property<string>("Valor");

                    b.Property<double>("ValorMensal");

                    b.Property<double>("ValorPorDia");

                    b.Property<double>("ValorPorHora");

                    b.HasKey("IdVeiculo");

                    b.ToTable("CARRO");
                });

            modelBuilder.Entity("Locadora.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarroId");

                    b.Property<string>("CategoriaCnh");

                    b.Property<string>("Cnh");

                    b.Property<string>("Cpf");

                    b.Property<int>("MotoId");

                    b.Property<string>("Nome");

                    b.Property<string>("PossuiReserva");

                    b.Property<string>("Rg");

                    b.Property<string>("Senha");

                    b.Property<string>("Status");

                    b.HasKey("IdCliente");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("Locadora.Models.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarroIdVeiculo");

                    b.Property<string>("Codigo");

                    b.Property<int?>("MotoIdVeiculo");

                    b.Property<string>("Nome");

                    b.HasKey("ModeloId");

                    b.HasIndex("CarroIdVeiculo");

                    b.HasIndex("MotoIdVeiculo");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("Locadora.Models.Moto", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoModelo");

                    b.Property<string>("Codigo");

                    b.Property<string>("CodigoFipe");

                    b.Property<string>("Combustivel");

                    b.Property<string>("Cor");

                    b.Property<string>("IdMarca");

                    b.Property<string>("IdModelo");

                    b.Property<string>("IdentVeiculo");

                    b.Property<string>("Imagem");

                    b.Property<string>("Marca");

                    b.Property<string>("MesReferencia");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nome");

                    b.Property<string>("Placa")
                        .IsRequired();

                    b.Property<double>("Preco");

                    b.Property<string>("Status");

                    b.Property<int>("TipoVeiculo");

                    b.Property<string>("Valor");

                    b.Property<double>("ValorMensal");

                    b.Property<double>("ValorPorDia");

                    b.Property<double>("ValorPorHora");

                    b.HasKey("IdVeiculo");

                    b.ToTable("MOTO");
                });

            modelBuilder.Entity("Locadora.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarroId");

                    b.Property<int>("ClienteId");

                    b.Property<DateTime>("DataPrevisaoDevolucao");

                    b.Property<DateTime>("DataReserva");

                    b.Property<DateTime>("DataVeiculoDevolvido");

                    b.Property<int>("MotoId");

                    b.Property<string>("Status");

                    b.Property<double>("ValorTotalReserva");

                    b.HasKey("IdReserva");

                    b.HasIndex("CarroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MotoId");

                    b.ToTable("RESERVA");
                });

            modelBuilder.Entity("Locadora.Models.Modelo", b =>
                {
                    b.HasOne("Locadora.Models.Carro")
                        .WithMany("Modelos")
                        .HasForeignKey("CarroIdVeiculo");

                    b.HasOne("Locadora.Models.Moto")
                        .WithMany("Modelos")
                        .HasForeignKey("MotoIdVeiculo");
                });

            modelBuilder.Entity("Locadora.Models.Reserva", b =>
                {
                    b.HasOne("Locadora.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Locadora.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Locadora.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
